/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rumahsakit;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Dokter extends javax.swing.JFrame {

    private DefaultTableModel model;

    /**
     * Creates new form Dokter
     */
    public Dokter() {
        initComponents();
        TampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        id_dokter = new javax.swing.JTextField();
        nama_dokter = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        tempat_lahir = new javax.swing.JTextField();
        tanggal_lahir = new com.toedter.calendar.JDateChooser();
        jenis_kelamin = new javax.swing.JComboBox<>();
        no_hp = new javax.swing.JTextField();
        spesialis = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(41, 83, 127));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DOKTER");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 120, 40));

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Id Dokter");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 90, 20));

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Nama Dokter");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 90, 20));

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Alamat");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 90, 20));

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Tempat Lahir");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 90, 20));

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Tanggal Lahir");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 90, 20));

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Jenis Kelamin");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 90, 20));

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("No Hp");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 80, 20));

        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Spesialis");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 100, 20));
        jPanel2.add(id_dokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 440, 20));

        nama_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_dokterActionPerformed(evt);
            }
        });
        jPanel2.add(nama_dokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 440, -1));
        jPanel2.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 440, -1));

        tempat_lahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempat_lahirActionPerformed(evt);
            }
        });
        jPanel2.add(tempat_lahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 440, -1));
        jPanel2.add(tanggal_lahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 440, -1));

        jenis_kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Laki-laki", "Perempuan" }));
        jPanel2.add(jenis_kelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 440, -1));
        jPanel2.add(no_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 440, -1));
        jPanel2.add(spesialis, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 440, -1));

        jButton1.setText("Input");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 60, -1));

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Dokter", "Nama Dokter", "Alamat", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "No Hp", "Spesialis"
            }
        ));
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 570, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nama_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_dokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_dokterActionPerformed

    private void tempat_lahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempat_lahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempat_lahirActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
            new Home().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        hapusdata();
        TampilData();
        bersih();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        simpandata();
        TampilData();
        bersih();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ubahdata();
        TampilData();
        bersih();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        // TODO add your handling code here:
                try {
            DefaultTableModel model = (DefaultTableModel)Tabel.getModel();
            int SelectedRowIndex = Tabel.getSelectedRow();
            
            id_dokter.setText(model.getValueAt(SelectedRowIndex, 0).toString());
            nama_dokter.setText(model.getValueAt(SelectedRowIndex, 1).toString());
            alamat.setText(model.getValueAt(SelectedRowIndex, 2).toString());
            tempat_lahir.setText(model.getValueAt(SelectedRowIndex, 3).toString());
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(SelectedRowIndex, 4));
            tanggal_lahir.setDate(date);
            jenis_kelamin.setSelectedItem(model.getValueAt(SelectedRowIndex, 5).toString());
            no_hp.setText(model.getValueAt(SelectedRowIndex, 6).toString());
            spesialis.setText(model.getValueAt(SelectedRowIndex, 7).toString());
            
        }catch (ParseException ex){
            
        }
    }//GEN-LAST:event_TabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel;
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField id_dokter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenis_kelamin;
    private javax.swing.JTextField nama_dokter;
    private javax.swing.JTextField no_hp;
    private javax.swing.JTextField spesialis;
    private com.toedter.calendar.JDateChooser tanggal_lahir;
    private javax.swing.JTextField tempat_lahir;
    // End of variables declaration//GEN-END:variables


//Codingan untuk tampil data
public void TampilData() {
    Object[] baris = {"id_dokter","nama_dokter","alamat","tempat_lahir","tanggal_lahir","jenis_kelamin","no_hp","spesialis"};

        model = new DefaultTableModel(null, baris);
        Tabel.setModel(model);
        Connection connection = new Koneksi().getConnection();
        try {
            String sql = "select * from Dokter order by id_dokter asc";
            java.sql.Statement statement = connection.createStatement();
            java.sql.ResultSet hasil = statement.executeQuery(sql);
            while (hasil.next()){
                String iddokter = hasil.getString("id_dokter");
                String namadokter = hasil.getString("nama_dokter");
                String Alamat = hasil.getString("alamat");
                String TmpLahir = hasil.getString("tempat_lahir");
                String TglLahir = hasil.getString("tanggal_lahir");
                String JnsKelamin = hasil.getString("jenis_kelamin");
                String No_HP = hasil.getString("no_hp");
                String Spesialis = hasil.getString("spesialis");
                String[] data = {iddokter, namadokter, Alamat, TmpLahir, TglLahir, JnsKelamin, No_HP, Spesialis};
                model.addRow(data);
            }
            
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, "Menampilkan data Gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null, "Menampilkan data Gagal" + e);
        }
}

//codingan untuk input data
void simpandata() {
    //Deklarasi variabel
    String iddokter = id_dokter.getText(); //nama text field di form
    String namadokter = nama_dokter.getText();
    String Alamat = alamat.getText();
    String TmpLahir = tempat_lahir.getText();
    String TglLahir = new SimpleDateFormat("yyyy-MM-dd").format(tanggal_lahir.getDate());
    String JnsKelamin = jenis_kelamin.getSelectedItem().toString();
    String No_HP = no_hp.getText();
    String Spesialis = spesialis.getText();
    
    
    
    //Koneksi terhadap database
    Connection connection = new Koneksi().getConnection();
    
    
    //Proses penyimpanan
    
    try {
        String sql = "Insert into Dokter values(?,?,?,?,?,?,?,?)"; //jumlah sesuai dengan variabel di tabel
      PreparedStatement statement = connection.prepareStatement(sql);
      //connection.prepareStatement(sql);
      
      
      statement.setString(1,iddokter);
      statement.setString(2,namadokter);
      statement.setString(3,Alamat);
      statement.setString(4,TmpLahir);
      statement.setString(5,TglLahir);
      statement.setString(6,JnsKelamin);
      statement.setString(7,No_HP);
      statement.setString(8,Spesialis);
      
      statement.executeUpdate();
      
      JOptionPane.showMessageDialog(null, "DATA BERHASIL DISIMPAN", "informasi", JOptionPane.INFORMATION_MESSAGE);
      
      //Jika data tidak berhasil diinput
      //TampilData();
      //Tambah fungsi refresh
    
    } catch (HeadlessException | SQLException e) {
       // JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN","informasi",);
       //JOptionPane.INFORMATION_MESSAGE;
       JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN \n" +e) ; //Gagal menampilkan data
    } 
    

    
    }

//codingan untuk input data
void ubahdata() {
    //Deklarasi variabel
    String iddokter = id_dokter.getText(); //nama text field di form
    String namadokter = nama_dokter.getText();
    String Alamat = alamat.getText();
    String TmpLahir = tempat_lahir.getText();
    String TglLahir = new SimpleDateFormat("yyyy-MM-dd").format(tanggal_lahir.getDate());
    String JnsKelamin = (String) jenis_kelamin.getSelectedItem();
    String No_HP = no_hp.getText();
    String Spesialis = spesialis.getText();
    
    
    //Koneksi terhadap database
    Connection connection = new Koneksi().getConnection();
    
    
    //Proses penyimpanan
    try {
        String sql = "update Dokter set nama_dokter=?, alamat=?, tempat_lahir=?, tanggal_lahir=?, jenis_kelamin=?, no_hp=?,  spesialis=? where id_dokter=?"; //jumlah sesuai dengan variabel di tabel
      PreparedStatement statement = connection.prepareStatement(sql);
      //connection.prepareStatement(sql);
      
      
      
      statement.setString(1,namadokter);
      statement.setString(2,Alamat);
      statement.setString(3,TmpLahir);
      statement.setString(4,TglLahir);
      statement.setString(5,JnsKelamin);
      statement.setString(6,No_HP);
      statement.setString(7,Spesialis);
      statement.setString(8,iddokter);

      
      statement.executeUpdate();
      
      JOptionPane.showMessageDialog(null, "DATA BERHASIL DIUBAH", "informasi", JOptionPane.INFORMATION_MESSAGE);
      
      //Jika data tidak berhasil diinput
      //TampilData();
      //Tambah fungsi refresh
    
    } catch (HeadlessException | SQLException e) {
       // JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN","informasi",);
       //JOptionPane.INFORMATION_MESSAGE;
       JOptionPane.showMessageDialog(null, "DATA GAGAL DIUBAH \n" +e) ; //Gagal menampilkan data
    } 
}


public void hapusdata(){
    
    int baris = Tabel.getSelectedRow();//namavariabeltabel pasien
    String id_dokter = model.getValueAt(baris, 0).toString();
    
    int Data = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin untuk menghapus data id_dokter :" +id_dokter+ "?",
            "konfirmasi", JOptionPane.YES_NO_OPTION); //primary key
    
    if (Data == 0){
        try {
            //memanggil method koneksi
            Connection connection = new Koneksi().getConnection();
            String sql = "delete from Dokter where id_dokter = '" +id_dokter + "'";
            Statement statement = connection.createStatement();
            statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            
            TampilData();
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Dataa Gagal Dihapus");
        }
    }
}

//Untuk kodingan bersih setelah proses 
public void bersih(){
    id_dokter.setText("");
    nama_dokter.setText("");
    alamat.setText("");
    tempat_lahir.setText("");
    new SimpleDateFormat("yyyy-MM-dd").format(tanggal_lahir.getDate());
    jenis_kelamin.setSelectedIndex(0);
    no_hp.setText("");
    spesialis.setText("");
}


}
