 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rumahsakit;

import javax.swing.DefaultButtonModel;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author ASUS
 */
public class Pasien extends javax.swing.JFrame {
    DefaultTableModel model;

    /**
     * Creates new form PASIEN
     */
    public Pasien() {
        initComponents();
        TampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        no_pasien = new javax.swing.JTextField();
        nama_pasien = new javax.swing.JTextField();
        TMP_L = new javax.swing.JTextField();
        HP = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        CmbJK = new javax.swing.JComboBox<>();
        TGL_L = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(41, 83, 127));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("PASIEN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("No Pasien");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 74, 110, 20));

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Nama Pasien");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, 20));

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Jenis Kelamin");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 120, 20));

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Tempat Lahir");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, 20));

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Tanggal Lahir");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 120, 20));

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("No Hp");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 110, 20));

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Alamat");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, 20));

        no_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_pasienActionPerformed(evt);
            }
        });
        jPanel1.add(no_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 310, -1));
        jPanel1.add(nama_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 310, -1));
        jPanel1.add(TMP_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 310, -1));
        jPanel1.add(HP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 310, -1));

        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 310, -1));

        CmbJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Laki-laki", "Perempuan" }));
        jPanel1.add(CmbJK, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 310, -1));
        jPanel1.add(TGL_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 310, -1));

        jButton1.setText("Input");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 70, -1));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, -1));

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No Pasien", "Nama Pasien", "Jenis Kelamin", "Tempat Lahir", "Tanggal Lahir", "No Hp", "Alamat"
            }
        ));
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 490, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        simpandata();
        TampilData();
        bersih();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
            new Home().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ubahdata();
        TampilData();
        bersih();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        hapusdata();
        TampilData();
        bersih();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        // TODO add your handling code here:
        try {
            DefaultTableModel model = (DefaultTableModel)Tabel.getModel();
            int SelectedRowIndex = Tabel.getSelectedRow();
            
            no_pasien.setText(model.getValueAt(SelectedRowIndex, 0).toString());
            nama_pasien.setText(model.getValueAt(SelectedRowIndex, 1).toString());
            CmbJK.setSelectedItem(model.getValueAt(SelectedRowIndex, 2).toString());
            TMP_L.setText(model.getValueAt(SelectedRowIndex, 3).toString());
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(SelectedRowIndex, 4));
            TGL_L.setDate(date);
            HP.setText(model.getValueAt(SelectedRowIndex, 5).toString());
            alamat.setText(model.getValueAt(SelectedRowIndex, 6).toString());
            
        }catch (ParseException ex){           
        }
    }//GEN-LAST:event_TabelMouseClicked

    private void no_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_pasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_pasienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbJK;
    private javax.swing.JTextField HP;
    private com.toedter.calendar.JDateChooser TGL_L;
    private javax.swing.JTextField TMP_L;
    private javax.swing.JTable Tabel;
    private javax.swing.JTextField alamat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nama_pasien;
    private javax.swing.JTextField no_pasien;
    // End of variables declaration//GEN-END:variables


    
//Codingan untuk tampil data
public void TampilData() {
    Object[] baris = {"no_pasien","nama_pasien","jenis_kelamin","tempat_lahir","tanggal_lahir","no_hp","alamat"};

        model = new DefaultTableModel(null, baris);
        Tabel.setModel(model);
        Connection connection = new Koneksi().getConnection();
        try {
            String sql = "select * from Pasien order by no_pasien asc";
            java.sql.Statement statement = connection.createStatement();
            java.sql.ResultSet hasil = statement.executeQuery(sql);
            while (hasil.next()){
                String nopasien = hasil.getString("no_pasien");
                String namapasien = hasil.getString("nama_pasien");
                String JnsKelamin = hasil.getString("jenis_kelamin");
                String TmpLahir = hasil.getString("tempat_lahir");
                String TglLahir = hasil.getString("tanggal_lahir");
                String No_HP = hasil.getString("no_hp");
                String Alamat = hasil.getString("alamat");
                String[] data = {nopasien, namapasien, JnsKelamin, TmpLahir, TglLahir, No_HP, Alamat};
                model.addRow(data);
            }
            
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, "Menampilkan data Gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null, "Menampilkan data Gagal" + e);
        }
}


//codingan untuk input data
void simpandata() {
    //Deklarasi variabel
    String nopasien = no_pasien.getText(); //nama text field di form
    String nama = nama_pasien.getText();
    String JK = CmbJK.getSelectedItem().toString();
    String tmpL = TMP_L.getText();
    String tgl = new SimpleDateFormat("yyyy-MM-dd").format(TGL_L.getDate());
    String hp = HP.getText();
    String almt = alamat.getText();
    
    
    
    //Koneksi terhadap database
    Connection connection = new Koneksi().getConnection();
    
    
    //Proses penyimpanan
    try {
        String sql = "Insert into pasien values(?,?,?,?,?,?,?)"; //jumlah sesuai dengan variabel di tabel
      PreparedStatement statement = connection.prepareStatement(sql);
      //connection.prepareStatement(sql);
      
      
      statement.setString(1,nopasien);
      statement.setString(2,nama);
      statement.setString(3,JK);
      statement.setString(4,tmpL);
      statement.setString(5,tgl);
      statement.setString(6,hp);
      statement.setString(7,almt);
      
      statement.executeUpdate();
      
      JOptionPane.showMessageDialog(null, "DATA BERHASIL DISIMPAN", "informasi", JOptionPane.INFORMATION_MESSAGE);
      
      //Jika data tidak berhasil diinput
      //TampilData();
      //Tambah fungsi refresh
    
    } catch (HeadlessException | SQLException e) {
       // JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN","informasi",);
       //JOptionPane.INFORMATION_MESSAGE;
       JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN \n" +e) ; //Gagal menampilkan data
    }     
    }

//codingan untuk input data
void ubahdata() {
    //Deklarasi variabel
    String nopasien = no_pasien.getText(); //nama text field di form
    String nama = nama_pasien.getText();
    String JK = CmbJK.getSelectedItem().toString();
    String tmpL = TMP_L.getText();
    String tgl = new SimpleDateFormat("yyyy-MM-dd").format(TGL_L.getDate());
    String hp = HP.getText();
    String almt = alamat.getText();
    
    
    
    //Koneksi terhadap database
    Connection connection = new Koneksi().getConnection();
    
    
    //Proses penyimpanan
    try {
        String sql = "update pasien set nama_pasien=?, jenis_kelamin=?, tempat_lahir=?, tanggal_lahir=?, no_hp=?, alamat=? where no_pasien=?"; //jumlah sesuai dengan variabel di tabel
      PreparedStatement statement = connection.prepareStatement(sql);
      //connection.prepareStatement(sql);
      
      
      
      statement.setString(1,nama);
      statement.setString(2,JK);
      statement.setString(3,tmpL);
      statement.setString(4,tgl);
      statement.setString(5,hp);
      statement.setString(6,almt);
      statement.setString(7,nopasien);
      
      statement.executeUpdate();
      
      JOptionPane.showMessageDialog(null, "DATA BERHASIL DIUBAH", "informasi", JOptionPane.INFORMATION_MESSAGE);
      
      //Jika data tidak berhasil diinput
      //TampilData();
      //Tambah fungsi refresh
    
    } catch (HeadlessException | SQLException e) {
       // JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN","informasi",);
       //JOptionPane.INFORMATION_MESSAGE;
       JOptionPane.showMessageDialog(null, "DATA GAGAL DIUBAH \n" +e) ; //Gagal menampilkan data
    } 
}


public void hapusdata(){
    
    int baris = Tabel.getSelectedRow();//namavariabeltabel pasien
    String no_pasien = model.getValueAt(baris, 0).toString();
    
    int Data = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin untuk menghapus data no_pasien :" +no_pasien+ "?",
            "konfirmasi", JOptionPane.YES_NO_OPTION); //primary key
    
    if (Data == 0){
        try {
            //memanggil method koneksi
            Connection connection = new Koneksi().getConnection();
            String sql = "delete from pasien where no_pasien = '" +no_pasien + "'";
            Statement statement = connection.createStatement();
            statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            
            TampilData();
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Dataa Gagal Dihapus");
        }
    }
}

//Untuk kodingan bersih setelah proses 
public void bersih(){
    no_pasien.setText("");
    nama_pasien.setText("");
    CmbJK.setSelectedIndex(0);
    TMP_L.setText("");
    new SimpleDateFormat("yyyy-MM-dd").format(TGL_L.getDate());
    HP.setText("");
    alamat.setText("");
}

}
