/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rumahsakit;

import javax.swing.DefaultButtonModel;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class perawat extends javax.swing.JFrame {

    private DefaultTableModel model;

    /**
     * Creates new form Perawat
     */
    public perawat() {
        initComponents();
        TampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id_perawat = new javax.swing.JTextField();
        nama_perawat = new javax.swing.JTextField();
        tempat_lahir = new javax.swing.JTextField();
        tanggal_lahir = new com.toedter.calendar.JDateChooser();
        jenis_kelamin = new javax.swing.JComboBox<>();
        no_hp = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(41, 83, 127));
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("PERAWAT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 130, 30));

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Id Perawat");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 90, 20));

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Nama Perawat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 90, 20));

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Tempat Lahir");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, 20));

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Tanggal Lahir");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 90, 20));

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Jenis Kelamin");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 90, 20));

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("No Hp");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 90, 20));

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Alamat");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 80, 20));
        jPanel1.add(id_perawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 410, -1));

        nama_perawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_perawatActionPerformed(evt);
            }
        });
        jPanel1.add(nama_perawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 410, -1));
        jPanel1.add(tempat_lahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 410, -1));
        jPanel1.add(tanggal_lahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 410, -1));

        jenis_kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Laki-laki", "Perempuan" }));
        jPanel1.add(jenis_kelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 410, -1));
        jPanel1.add(no_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 410, -1));
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 410, -1));

        jButton1.setText("Input");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, -1));

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Perawat", "Nama Perawat", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "No Hp", "Alamat"
            }
        ));
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 540, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nama_perawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_perawatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_perawatActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ubahdata();
        TampilData();
        bersih();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
            new Home().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        simpandata();
        TampilData();
        bersih();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        // TODO add your handling code here:
        try {
            DefaultTableModel model = (DefaultTableModel)Tabel.getModel();
            int SelectedRowIndex = Tabel.getSelectedRow();
            
            id_perawat.setText(model.getValueAt(SelectedRowIndex, 0).toString());
            nama_perawat.setText(model.getValueAt(SelectedRowIndex, 1).toString());
            tempat_lahir.setText(model.getValueAt(SelectedRowIndex, 2).toString());
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(SelectedRowIndex, 3));
            tanggal_lahir.setDate(date);
            jenis_kelamin.setSelectedItem(model.getValueAt(SelectedRowIndex, 4).toString());
            no_hp.setText(model.getValueAt(SelectedRowIndex, 5).toString());
            alamat.setText(model.getValueAt(SelectedRowIndex, 6).toString());
            
        }catch (ParseException ex){
            
        }
    }//GEN-LAST:event_TabelMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        hapusdata();
        TampilData();
        bersih();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perawat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel;
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField id_perawat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenis_kelamin;
    private javax.swing.JTextField nama_perawat;
    private javax.swing.JTextField no_hp;
    private com.toedter.calendar.JDateChooser tanggal_lahir;
    private javax.swing.JTextField tempat_lahir;
    // End of variables declaration//GEN-END:variables

//Codingan untuk tampil data
public void TampilData() {
   Object[] baris = {"id_perawat","nama_perawat","tempat_lahir","tanggal_lahir","jenis_kelamin","no_hp","alamat"};

        model = new DefaultTableModel(null, baris);
        Tabel.setModel(model);
        Connection connection = new Koneksi().getConnection();
        try {
            String sql = "select * from Perawat order by id_perawat asc";
            java.sql.Statement statement = connection.createStatement();
            java.sql.ResultSet hasil = statement.executeQuery(sql);
            while (hasil.next()){
                String idperawat = hasil.getString("id_perawat");
                String perawat = hasil.getString("nama_perawat");
                String TmpLahir = hasil.getString("tempat_lahir");
                String TglLahir = hasil.getString("tanggal_lahir");
                String JnsKelamin = hasil.getString("jenis_kelamin");
                String No_HP = hasil.getString("no_hp");
                String Alamat = hasil.getString("alamat");
                String[] data = {idperawat, perawat, TmpLahir, TglLahir, JnsKelamin, No_HP, Alamat};
                model.addRow(data);
            }
            
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, "Menampilkan data Gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null, "Menampilkan data Gagal" + e);
        }
}


void simpandata(){
    //Deklarasi variabel
    String idperawat = id_perawat.getText(); //nama text field di form
    String perawat = nama_perawat.getText();
    String TmpLahir = tempat_lahir.getText();
    String TglLahir = new SimpleDateFormat("yyyy-MM-dd").format(tanggal_lahir.getDate());
    String JnsKelamin = jenis_kelamin.getSelectedItem().toString();
    String No_HP = no_hp.getText();
    String Alamat = alamat.getText();
    
    
    //Koneksi terhadap database
    Connection connection = new Koneksi().getConnection();
    
    
    //Proses penyimpanan
    try{
        String sql = "insert into perawat values(?,?,?,?,?,?,?)";
        PreparedStatement statement = connection.prepareStatement(sql);
        //connection.prepareStatement(sql);
        
        statement.setString(1, idperawat);
        statement.setString(2, perawat);
        statement.setString(3, TmpLahir);
        statement.setString(4, TglLahir);
        statement.setString(5, JnsKelamin);
        statement.setString(6, No_HP);
        statement.setString(7, Alamat);
        
        statement.executeUpdate();
        
        JOptionPane.showMessageDialog(null, "DATA BERHASIL DISIMPAN","informasi",JOptionPane.INFORMATION_MESSAGE);
        
    }catch (HeadlessException | SQLException e) {
      
        JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN \n"); //Menampilkan laporan data gagal disimpan
    }
}

//codingan untuk input data
void ubahdata() {
    //Deklarasi variabel
    String idperawat = id_perawat.getText(); //nama text field di form
    String perawat = nama_perawat.getText();
    String TmpLahir = tempat_lahir.getText();
    String TglLahir = new SimpleDateFormat("yyyy-MM-dd").format(tanggal_lahir.getDate());
    String JnsKelamin = jenis_kelamin.getSelectedItem().toString();
    String No_HP = no_hp.getText();
    String Alamat = alamat.getText();
    
    
    
    //Koneksi terhadap database
    Connection connection = new Koneksi().getConnection();
    
    
    //Proses penyimpanan
    try {
        String sql = "update perawat set nama_perawat=?, tempat_lahir=?, tanggal_lahir=?, jenis_kelamin=?, no_hp=?, alamat=? where id_perawat=?"; //jumlah sesuai dengan variabel di tabel
      PreparedStatement statement = connection.prepareStatement(sql);
      //connection.prepareStatement(sql);
      
      
      
      statement.setString(1,perawat);
      statement.setString(2,TmpLahir);
      statement.setString(3,TglLahir);
      statement.setString(4,JnsKelamin);
      statement.setString(5,No_HP);
      statement.setString(6,Alamat);
      statement.setString(7,idperawat);
      
      statement.executeUpdate();
      
      JOptionPane.showMessageDialog(null, "DATA BERHASIL DIUBAH", "informasi", JOptionPane.INFORMATION_MESSAGE);
      
      //Jika data tidak berhasil diinput
      //TampilData();
      //Tambah fungsi refresh
    
    } catch (HeadlessException | SQLException e) {
       // JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN","informasi",);
       //JOptionPane.INFORMATION_MESSAGE;
       JOptionPane.showMessageDialog(null, "DATA GAGAL DIUBAH \n" +e) ; //Gagal menampilkan data
    } 
}

public void hapusdata(){
    
    int baris = Tabel.getSelectedRow();//namavariabeltabel pasien
    String id_perawat = model.getValueAt(baris, 0).toString();
    
    int Data = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin untuk menghapus data id_perawat :" +id_perawat+ "?",
            "konfirmasi", JOptionPane.YES_NO_OPTION); //primary key
    
    if (Data == 0){
        try {
            //memanggil method koneksi
            Connection connection = new Koneksi().getConnection();
            String sql = "delete from perawat where id_perawat = '" +id_perawat + "'";
            Statement statement = connection.createStatement();
            statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            
            TampilData();
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Dataa Gagal Dihapus");
        }
    }
}

//Untuk kodingan bersih setelah proses 
public void bersih(){
    id_perawat.setText("");
    nama_perawat.setText("");
    tempat_lahir.setText("");
    new SimpleDateFormat("yyyy-MM-dd").format(tanggal_lahir.getDate());
    jenis_kelamin.setSelectedIndex(0);
    no_hp.setText("");
    alamat.setText("");
}


}
