/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rumahsakit;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class RawatJalan extends javax.swing.JFrame {
    RS rs = new RS();

    /**
     * Creates new form RawatJalan
     */
    public RawatJalan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Konfirmasi = new javax.swing.JButton();
        daftar = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        namaP = new javax.swing.JTextField();
        TMPL = new javax.swing.JTextField();
        HP = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        JK = new javax.swing.JComboBox<>();
        cbPasien = new javax.swing.JComboBox<>();
        cbDokter = new javax.swing.JComboBox<>();
        ttlK = new javax.swing.JTextField();
        TGL_L = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Silahkan Masukan Data Pasien");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 94, -1, -1));

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 136, -1, -1));

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Jenis kelamin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 164, 93, 32));

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Tempat lahir");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 207, -1, -1));

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Tanggal Lahir");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 242, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("RAWAT JALAN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 41, -1, -1));

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("No HP ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 280, -1, -1));

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Alamat");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 318, -1, -1));

        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Pilih Status Pasien");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 356, -1, -1));

        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Pilih Dokter ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 394, -1, -1));

        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Total Keseluruhan");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 432, -1, -1));

        Konfirmasi.setText("Konfirmasi");
        Konfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KonfirmasiActionPerformed(evt);
            }
        });
        getContentPane().add(Konfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, -1, -1));

        daftar.setText("Daftar");
        daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarActionPerformed(evt);
            }
        });
        getContentPane().add(daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, -1, -1));

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        namaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPActionPerformed(evt);
            }
        });
        getContentPane().add(namaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 133, 362, -1));

        TMPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TMPLActionPerformed(evt);
            }
        });
        getContentPane().add(TMPL, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 201, 362, -1));
        getContentPane().add(HP, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 277, 362, -1));
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 315, 362, -1));

        JK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Laki-laki", "Perempuan" }));
        getContentPane().add(JK, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 163, 362, -1));

        cbPasien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SILAHKAN ISI", "PASIEN ASURANSI", "PASIEN UMUM", "PASIEN BPJS", " " }));
        cbPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPasienActionPerformed(evt);
            }
        });
        getContentPane().add(cbPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 353, 362, -1));

        cbDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SILAHKAN ISI", "dr. Budi Herdansyah", "dr. Selly Wijaksana", "dr. Anies Simatupang", "dr. Triana Apriani" }));
        cbDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDokterActionPerformed(evt);
            }
        });
        getContentPane().add(cbDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 391, 362, -1));

        ttlK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttlKActionPerformed(evt);
            }
        });
        getContentPane().add(ttlK, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 429, 362, -1));
        getContentPane().add(TGL_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 360, -1));

        jPanel1.setBackground(new java.awt.Color(41, 83, 127));
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KonfirmasiActionPerformed
        // TODO add your handling code here:
        ttlK.setText(Double.toString(rs.getTtl()));
    }//GEN-LAST:event_KonfirmasiActionPerformed

    private void ttlKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttlKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttlKActionPerformed

    private void cbPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPasienActionPerformed
        // TODO add your handling code here:
        rs.setPasien(cbPasien.getSelectedItem().toString());
        rs.setSeleksiPasien();
        rs.getBiayapasien();
        
    }//GEN-LAST:event_cbPasienActionPerformed

    private void cbDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDokterActionPerformed
        // TODO add your handling code here:
        rs.setDokter(cbDokter.getSelectedItem().toString());
        rs.setSeleksiDokter();
        rs.getBiayaDokter();
    }//GEN-LAST:event_cbDokterActionPerformed

    private void daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarActionPerformed
        // TODO add your handling code here:
        simpandata();
    }//GEN-LAST:event_daftarActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HomeP().setVisible(true);
    }//GEN-LAST:event_kembaliActionPerformed

    private void TMPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TMPLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TMPLActionPerformed

    private void namaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RawatJalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RawatJalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RawatJalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RawatJalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RawatJalan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HP;
    private javax.swing.JComboBox<String> JK;
    private javax.swing.JButton Konfirmasi;
    private com.toedter.calendar.JDateChooser TGL_L;
    private javax.swing.JTextField TMPL;
    private javax.swing.JTextField alamat;
    private javax.swing.JComboBox<String> cbDokter;
    private javax.swing.JComboBox<String> cbPasien;
    private javax.swing.JButton daftar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField namaP;
    private javax.swing.JTextField ttlK;
    // End of variables declaration//GEN-END:variables

void simpandata() {
    //Deklarasi variabel
    String namapasien = namaP.getText(); //nama text field di form
    String jeniskelamin = JK.getSelectedItem().toString();
    String tmpL = TMPL.getText();
    String tgl = new SimpleDateFormat("yyyy-MM-dd").format(TGL_L.getDate());
    String hp = HP.getText();
    String almt = alamat.getText();
    String spas = cbPasien.getSelectedItem().toString();
    String dokter = cbDokter.getSelectedItem().toString();
    String total = ttlK.getText();
    
    //Koneksi terhadap database
    Connection connection = new Koneksi().getConnection();
    
    
    //Proses penyimpanan
    try {
        String sql = "Insert into datarawatjalan values(?,?,?,?,?,?,?,?,?)"; //jumlah sesuai dengan variabel di tabel
      PreparedStatement statement = connection.prepareStatement(sql);
      //connection.prepareStatement(sql);
      
      
      statement.setString(1,namapasien);
      statement.setString(2,jeniskelamin);
      statement.setString(3,tmpL);
      statement.setString(4,tgl);
      statement.setString(5,hp);
      statement.setString(6,almt);
      statement.setString(7,spas);
      statement.setString(8,dokter);
      statement.setString(9,total);
      
     
      
      statement.executeUpdate();
      
      JOptionPane.showMessageDialog(null, "Berhasil daftar", "informasi", JOptionPane.INFORMATION_MESSAGE);
      
      //Jika data tidak berhasil diinput
      //TampilData();
      //Tambah fungsi refresh
    
    } catch (HeadlessException | SQLException e) {
       // JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN","informasi",);
       //JOptionPane.INFORMATION_MESSAGE;
       JOptionPane.showMessageDialog(null, "Gagal Daftar \n" +e) ; //Gagal menampilkan data
    }
    
    }
}

